FROM node:14

WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]

RUN npm install -f
COPY . .
COPY .env.production .env
RUN npm run build



EXPOSE 8080

ENV NODE_ENV production

CMD ["node", "dist/index.js"]
USER node